name: Sync multiple branches
on:
  workflow_run:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Merge development -> main
        uses: devmasx/merge-branch@v1.4
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ github.token }}
